### ISSUE TITLE
Famicom Disk System support

### ISSUE THREAD

**Issue by tatsutron** [pocomane/MiSTer_Batch_Control#17]
I've noticed when testing that running FDS games with the `NES` id works, whereas it doesn't work if I use `NES.FDS` instead. Maybe the latter is no longer needed? (Or I might just be misunderstanding something)

**Comment by pocomane** [comment]
I think that the two items in the MiSTer menu were merged, so `NDS.FDS` started to select the wrong menu item. However in my setup I can not load FDS games with `NES` id, so I fixed the `NDS.FDS`. Now it should be able to correctly launch the roms.

**Comment by tatsutron** [comment]
I've updated to the latest release, and `NES.FDS` works like a charm -- thanks as always!
