### ISSUE TITLE
Support darksoft neo geo format

### ISSUE THREAD

**Issue by tatsutron** [pocomane/MiSTer_Batch_Control#23]

**Comment by pocomane** [comment]
What is the "darksoft neo geo format" and how it is different from the standard neo geo format? In any case, I moved mbc to the new MGL feature, so if darksoft is supported by MGL, it should be supported by mbc too.

Can you check if it works with the last commit?

**Comment by tatsutron** [comment]
For completeness, DarkSoft format was, IIRC, a format from a particular Neo Geo flash cart. The format split roms up into multiple files rather than a single ROM like `.neo`. These ROMs are (or were) supported by the Neo Geo MiSTer core. I think your approach of just supporting whatever MGL supports makes perfect sense though FWIW.
