### ISSUE TITLE
Saturn support

### ISSUE THREAD

**Issue by felleg** [pocomane/MiSTer_Batch_Control#33]
It seems like the Saturn is not yet included in the `mbc list_core` command. Is this something that could be implemented in the near future?

Thanks for the great tool. :)

**Comment by tatsutron** [comment]
@pocomane I can get this in relatively soon if you're busy with other stuff. Just let me know :+1:

**Comment by pocomane** [comment]
The change is quite simple, I just need to find the time to find a saturn iso and make some test. I was planning to do it in this weekend since I am bit busy. @tatsutron if you can/want make a PR I would accept it for sure :)

**Comment by pocomane** [comment]
With the last commit, Saturn .cue images should work.

**Comment by felleg** [comment]
Working great! Many thanks :)
