### ISSUE TITLE
rom-mount feature works but various error messages

### ISSUE THREAD

**Issue by mrchrisster** [pocomane/MiSTer_Batch_Control#8]
Thanks for implementing the new rom mount feature. The feature seems to work with CIFS but I'm currently getting the following error messages:

`511 - error - Resource busy - Can not remove /media/fat/games/Genesis
437 - retrying the unbinding since the mount point is busy (/media/fat/games/Genesis/~~~.gen)
511 - error - Resource busy - Can not remove /media/fat/games/Genesis`

**Comment by pocomane** [comment]
Is this still an issue, or it was a false positive?

**Comment by mrchrisster** [comment]
It seems to work well despite the messages. It does eventually work on the retries, so we can close this
